### ISSUE TITLE
[TT-015] Backup & Restore

### ISSUE THREAD

**Issue by NarrowCode** [sw21-tug/Team_02#15]
**As a**
user with a lot of tasks

**I want to**
be able to export all my tasks and categories in a file that I can restore later

**so that**
I have a backup of my data

**additional information**
The file can be stored in the emulated storage, no need to provide a complete file dialog.
It is sufficient to have 1 backup file that gets overwritten on each export.
Restore always restores that file.

**Acceptance criteria**
- [ ] User can export tasks, categories
- [ ] User can import tasks, categories

**Comment by steschi** [comment]
Size: 5

**Comment by yb1998** [comment]
How to Backup / Insert Rooms DB
https://medium.com/@tonia.tkachuk/how-to-export-room-database-to-csv-file-a51fec589618
https://stackoverflow.com/questions/50987119/backup-room-database

Tool for Backup:
https://github.com/usupsuparma/Backup-and-Restore-RoomDatabase
https://github.com/rafi0101/Android-Room-Database-Backup
