### ISSUE TITLE
[TT-018] Dark mode

### ISSUE THREAD

**Issue by NarrowCode** [sw21-tug/Team_02#18]
**As a**
user with the urge to customize everything

**I want to**
be able to use dark mode in the application

**so that**
users that have dark mode enabled can read the text properly

**Acceptance criteria**
- [x] Users can enable / disable dark mode in the menu

**Comment by steschi** [comment]
Size: 5

**Comment by NarrowCode** [comment]
Icons from https://material.io/ (Dark and Light mode)
