### ISSUE TITLE
[TT-028] App Icon

### ISSUE THREAD

**Issue by NarrowCode** [sw21-tug/Team_02#78]
**As a**
user with a lot of applications on my phone

**I want to**
have a custom app icon

**so that**
I can find the application in my app drawer

**Comment by yb1998** [comment]
[AppIcons.zip](https://github.com/sw21-tug/Team_02/files/6614573/AppIcons.zip)

**Comment by yb1998** [comment]
[Icon_v2.zip](https://github.com/sw21-tug/Team_02/files/6621257/Icon_v2.zip)
